# Generated by Django 5.2.1 on 2025-06-19 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visitedplace",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="visitedplace",
            unique_together={("user", "name", "address")},
        ),
    ]
