# Generated by Django 5.2.1 on 2025-06-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_visitedplace_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitedplace",
            name="visit_date",
        ),
        migrations.AddField(
            model_name="visitedplace",
            name="last_visited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
