# Generated by Django 5.2.1 on 2025-06-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_remove_visitedplace_visit_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitedplace",
            name="purchase_total",
        ),
    ]
