# Generated by Django 5.1.4 on 2025-01-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paperkeep", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineitem",
            old_name="total_price",
            new_name="price",
        ),
    ]
