# Generated by Django 5.1.4 on 2025-02-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paperkeep", "0002_rename_total_price_lineitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialdocument",
            name="document_number",
        ),
    ]
