# Generated by Django 5.2.1 on 2025-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_systemspendingcategory_userspendingcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdocument",
            name="business_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="business_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="transaction_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="item",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
