# Generated by Django 5.2.1 on 2025-06-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_financialdocument_business_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdocument",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="financialdocument",
            name="tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
