# Generated by Django 5.2.1 on 2025-06-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_financialdocument_subtotal_financialdocument_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdocument",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
