# Generated by Django 5.2.1 on 2025-06-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_financialdocument_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdocument",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
