# Generated by Django 5.2.1 on 2025-06-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_financialdocument_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdocument",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="financialdocument",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
