# Generated by Django 5.2.1 on 2025-06-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("main", "0008_alter_financialdocument_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdocument",
            name="visited_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="analytics.visitedplace",
            ),
        ),
    ]
