# Generated by Django 5.2.1 on 2025-06-20 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_financialdocument_visited_place"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userspendingcategory",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="userspendingcategory",
            unique_together={("user", "system_category", "is_main")},
        ),
    ]
