# Generated by Django 5.2.1 on 2025-06-20 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_userspendingcategory_is_main_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category")},
        ),
    ]
