# Generated by Django 5.2.1 on 2025-06-23 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_budget_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdocument",
            name="upload_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
