# Generated by Django 5.2.1 on 2025-06-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_financialdocument_upload_datetime"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userspendingcategory",
            unique_together=set(),
        ),
    ]
